Repository team-xquare/xquare-infrastructure-global, pull requests merged in 2023-07, with the labels that each got.

#1 🔀 :: 테스트
  main.tf
Labels: 테스트 추가

#2 🔀 :: stag ecr 추가
  local.tf
  main.tf
Labels: 기능 추가

#3 🔀 :: create vpc
  data.tf
  local.tf
  main.tf
Labels: 기능 추가

#4 🔀 :: create eks cluster
  local.tf
  main.tf
  outputs.tf
Labels: 기능 추가

#6 🔀 :: local 변수 사용해서 분리
  local.tf
  provider.tf
Labels: chore, 리팩토링
